export const theme = {
  breakpoints: ['375px', '768px', '1440px'],
  colors: {},
  fonts: {},
  borders: {},
  radii: {},
};
export const colors = {
  primaryBlack: '#1E1F28',
  colorAccent: '#8BAA36',
  greenSecondary: '#EBF3D4',
  success: '#3CBC81',
  warning: '#F6C23E',
  error: '#E74A3B',
  whiteText: '#FAFAFA',
  grey: `#D9D9D9`,
  white: '#ffffff',
  whiteToggle: '#EFEFEF',
  black: '#000000',
  titleConteiner: `#001833`,
  button: {
    textColorMain: '#FAFAFA',
    hoverTextColorMain: '#22252A',
    hoverSecondaryText: '#8BAA36',
    cancelPrimaryBag: '#D9D9D9',
    cancelSecondaryBag: '#FFFFFF',
    primaryBag: '#8BAA36',
    secondaryBag: '#22252A',
  },

  form: {
    inpBorder: '#FFFFFF',
    inpConfirm: '#3CBC81',
    inpWarning: '#F6C23E',
    inpError: '#E74A3B',
    formIcon: '#FAFAFA',
    formBottomLine: '#E0E0E0',
    formBackground: '#2a2c36',
    formIngredientsBackground: '#F5F5F5',
    formAddText: '#7d7d7d',
    formAddIcon: '#333333',
    labelText: '#000000',
  },
};
